### ISSUE TITLE
Incorrect http re-assembly

### ISSUE THREAD

**Issue by kjk** [ga0/netgraph#10]
[trace_indexes_from_client_go.pcap.zip](https://github.com/ga0/netgraph/files/2259305/trace_indexes_from_client_go.pcap.zip)

Attached is pcap file that is incorrectly re-assembled into http stream.

As seen in this screenshot, the body of DELETE request is not correct:

<img width="1143" alt="screen shot 2018-08-04 at 1 01 12 am" src="https://user-images.githubusercontent.com/7935/43674047-375f4e08-9782-11e8-93a7-60970e404dc0.png">

To make sure it's not a bad pcap file, I looked at packets using http://www.tastycocoabytes.com/cpa/.

This is how body of the request should look like:

<img width="254" alt="screen shot 2018-08-04 at 1 03 45 am" src="https://user-images.githubusercontent.com/7935/43674063-7baadd66-9782-11e8-98dc-cdf471a75b6b.png">

I used `netgraph -input-pcap trace_indexes_from_client_go.pcap`

**Comment by kjk** [comment]
I think https://github.com/ga0/netgraph/blob/master/ngnet/httpstream.go#L74 might be an issue.

It merely sends r for processing.

According to https://godoc.org/github.com/google/gopacket/tcpassembly#Stream, []Reassembly slice will be re-used, so probably should make a copy of r before sending.

**Comment by ga0** [comment]
Thank you for posting this issue!
I'll try to solve it.

**Comment by ga0** [comment]
I missed to copy data from buffer  [here](https://github.com/ga0/netgraph/blob/5e67cc21772165e0ae562ad7a85374d2ac41f047/ngnet/streamreader.go#L72), if you are interested.
