### ISSUE TITLE
请求无法侦的问题

### ISSUE THREAD

**Issue by liubangde88** [ga0/netgraph#13]
我的8888 端口是一个http 代理，使用的ip 是 192.168.33.10
root@stretch:~# netstat -ano|grep 8888
tcp6       0      0 :::8888                 :::*                    LISTEN      off (0.00/0/0)
tcp6       0      0 192.168.33.10:8888      192.168.33.1:52950      ESTABLISHED keepalive (14.74/0/0)
tcp6       0      0 192.168.33.10:8888      192.168.33.1:53477      FIN_WAIT2   timewait (48.60/0/0)
tcp6       0      0 192.168.33.10:8888      192.168.33.1:53018      ESTABLISHED keepalive (2.46/0/0)

该ip 在 eth1 网卡上面
eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.33.10  netmask 255.255.255.0  broadcast 192.168.33.255
        inet6 fe80::a00:27ff:fec3:4005  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:c3:40:05  txqueuelen 1000  (Ethernet)
        RX packets 6808  bytes 753436 (735.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9798  bytes 8891562 (8.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

我通过  go/bin/netgraph -bpf "tcp port 8888" -i eth1
侦听eth1网卡上面的8888 端口， 然后并没有请求该代理上的请求包信息
请问是我那个步骤是错误的吗？

**Comment by liubangde88** [comment]
首先已经确认eht0 也侦听不到

**Comment by liubangde88** [comment]
我找到问题了，是因为嗅探器并不能侦听https 的请求， 是这样吗？ 可否有解决方案

**Comment by ga0** [comment]
你好，由于 HTTPS 是加密的，本身就是以防止嗅探为目的的，理论上是无法解决的。
