### ISSUE TITLE
about: cannot allocate memory

### ISSUE THREAD

**Issue by phpor** [ga0/netgraph#2]
I can captrue pacage use tcpdump ; but I get into trouble when use netgraph ,like this:

2016/01/12 13:01:26 lo: can't create rx ring on packet socket: Cannot allocate memory

What's wrong with me？
thanks for your help！

**Comment by ga0** [comment]
你的操作系统是？
你是使用什么命令启动的netgraph?
是启动多久之后出现的该错误提示？
是不是内存占用很高？

请提供上述信息，谢谢你的反馈！

**Comment by phpor** [comment]
同样的启动方法，在mac上没有问题，在centos6.5上就启动不了，直接报上面的错误。启动方法参考的你的文档，难道启动就需要很多内存，strace跟了下，也没发现申请内存方面的错误，怀疑和权限有关系，但是用tcpdump抓包是没问题的，所以，满心欢喜地去学习，结果却有些沮丧，多谢支持！

**Comment by ga0** [comment]
我只在Centos7上测试过。
我会在Centos6.5上测试一下找找原因。
多谢~！

**Comment by ga0** [comment]
新版本没有发现问题
