### ISSUE TITLE
公司需要抓取网卡的镜像数据，能不能给个联系方式 ，需要支持，可付费。

### ISSUE THREAD

**Issue by pgyggi** [ga0/netgraph#4]
公司需要抓取网卡的镜像数据，能不能给个联系方式 ，需要支持，可付费。

**Comment by ga0** [comment]
如果有bug，或者新的需求，我确认之后，会进行修改。
欢迎提交新Issue。
有更多的人使用和喜欢这个程序就是最大的收获，我会尽力支持，不需要收费 :)。
